Allow enabling and disabling persistence of individual components (output, environment, history, working directory)

diff --git a/bash_sessions b/bash_sessions
--- a/bash_sessions
+++ b/bash_sessions
@@ -136,6 +136,7 @@ o (){
 # switch to dedicated history file
 if [ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/history" ]; then
 	history -c
+	export BASH_SESSIONS_OLD_HISTFILE="${HISTFILE}"
 	export HISTFILE="${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/history"
 fi
 
@@ -334,6 +335,88 @@ a (){
 	done
 }
 
+# change settings for active session
+S (){
+	# check number of arguments
+	if [ "$#" -ne 2 ]; then
+		echo "Error: ${FUNCNAME[0]}() requires exactly 2 arguments"
+		return
+	fi
+
+	# check that we are in a session
+	if [ -z "${BASH_SESSION_NAME}" ]; then
+		echo "No session active!"
+		return
+	fi
+
+	if [ "${1}" == "output" ]; then
+		if [ "${2}" == "on" ]; then
+			if ! [ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output" ]; then
+				touch "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output"
+				echo "bash_session: saving output requires exiting and re-entering session to become effective"
+			fi
+		elif [ "${2}" == "off" ]; then
+			if [ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output" ]; then
+				rm "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/output"
+			fi
+		else
+			echo "bash_sessions: invalid argument \"${2}\""
+		fi
+
+	elif [ "${1}" == "pwd" ]; then
+		if [ "${2}" == "on" ]; then
+			if ! [ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/pwd" ]; then
+				export PROMPT_COMMAND="${PROMPT_COMMAND};__bs_savepwd"
+			fi
+		elif [ "${2}" == "off" ]; then
+			if [ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/pwd" ]; then
+				rm "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/pwd"
+				export PROMPT_COMMAND="${PROMPT_COMMAND/;__bs_savepwd/}"
+			fi
+		else
+			echo "bash_sessions: invalid argument \"${2}\""
+		fi
+
+	elif [ "${1}" == "env" ]; then
+		if [ "${2}" == "on" ]; then
+			if ! [[ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/env_changed" && -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/env_deleted" ]]; then
+				export PROMPT_COMMAND="${PROMPT_COMMAND};__bs_saveenv"
+			fi
+		elif [ "${2}" == "off" ]; then
+			if [ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/env_changed" ]; then
+				rm "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/env_changed"
+			fi
+			if [ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/env_deleted" ]; then
+				rm "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/env_deleted"
+			fi
+			export PROMPT_COMMAND="${PROMPT_COMMAND/;__bs_saveenv/}"
+		else
+			echo "bash_sessions: invalid argument \"${2}\""
+		fi
+
+	elif [ "${1}" == "history" ]; then
+		if [ "${2}" == "on" ]; then
+			if ! [ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/history" ]; then
+				tail -n 100 "${HISTFILE}" > "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/history"
+				history -c
+				export BASH_SESSIONS_OLD_HISTFILE="${HISTFILE}"
+				export HISTFILE="${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/history"
+			fi
+		elif [ "${2}" == "off" ]; then
+			if [ -f "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/history" ]; then
+				export HISTFILE="${BASH_SESSIONS_OLD_HISTFILE}"
+				rm "${BASH_SESSIONS_DIR}/${BASH_SESSION_NAME}/history"
+			fi
+		else
+			echo "bash_sessions: invalid argument \"${2}\""
+		fi
+
+	else
+		echo "bash_sessions: invalid argument \"${1}\""
+
+	fi
+}
+
 # print label for bash prompt
 __bs_ps1 (){
 	if [ -n "${BASH_SESSION_NAME}" ]; then
@@ -362,28 +445,56 @@ function e {
 	done
 }
 
-# helper function for completion
-function __bs_comp_list {
-	
+# helper function for sessions completion
+function __bs_sessions_comp_list {
 	# create sessions directory if needed
 	[ -d "${BASH_SESSIONS_DIR}" ] || mkdir -p "${BASH_SESSIONS_DIR}"
 	
 	ls "${BASH_SESSIONS_DIR}"
 }
 
-# completion command
-function _bash_session_comp {
-	local curw
+# helper function for options completion
+function __bs_options_comp_list {
+	echo "output"
+	echo "pwd"
+	echo "env"
+	echo "history"
+}
+
+# helper function for option values completion
+function __bs_values_comp_list {
+	echo "on"
+	echo "off"
+}
+
+# completion command for sessions
+function __bs_sessions_comp {
 	COMPREPLY=()
-	curw=${COMP_WORDS[COMP_CWORD]}
-	COMPREPLY=($(compgen -W '`__bs_comp_list`' -- $curw))
+	local current_word=${COMP_WORDS[COMP_CWORD]}
+	COMPREPLY=($(compgen -W '`__bs_sessions_comp_list`' -- ${current_word}))
+	return 0
+}
+
+# completion command for options
+function __bs_options_comp {
+	COMPREPLY=()
+	local current_word=${COMP_WORDS[COMP_CWORD]}
+	local previous_word=${COMP_WORDS[COMP_CWORD-1]}
+	case "${previous_word}" in
+		"S") COMPREPLY=($(compgen -W '`__bs_options_comp_list`' -- ${current_word}));;
+		"output") COMPREPLY=($(compgen -W '`__bs_values_comp_list`' -- ${current_word}));;
+		"pwd") COMPREPLY=($(compgen -W '`__bs_values_comp_list`' -- ${current_word}));;
+		"env") COMPREPLY=($(compgen -W '`__bs_values_comp_list`' -- ${current_word}));;
+		"history") COMPREPLY=($(compgen -W '`__bs_values_comp_list`' -- ${current_word}));;
+	esac
 	return 0
 }
 
 
-# bind completion command for o, f, r to _comp
+# bind completion commands
 shopt -s progcomp
-complete -o filenames -F _bash_session_comp o
-complete -o filenames -F _bash_session_comp f
-complete -o filenames -F _bash_session_comp r
+complete -o filenames -F __bs_sessions_comp o
+complete -o filenames -F __bs_sessions_comp f
+complete -o filenames -F __bs_sessions_comp r
+complete -F __bs_options_comp S
 
